version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  
  eureka-server:
    container_name: eureka-server
    image: eureka-server
    build: https://github.com/elvint14/eureka-server.git
    ports:
      - "8761:8761"
    depends_on:
      - postgres
  
  zuul-gateway-server:
    container_name: zuul-gateway-server
    image: zuul-gateway-server
    build: https://github.com/elvint14/zuul-gateway-server.git
#       context: zuul-gateway-server
#       dockerfile: ./zuul-gateway-server/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - eureka-server
  
  auth-service:
    container_name: auth-service
    image: auth-service
    build: https://github.com/elvint14/auth-service.git
#       context: auth-service
#       dockerfile: ./auth-service/Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - zuul-gateway-server
      - postgres

  order-service:
    container_name: order-service
    image: order-service
    build: https://github.com/elvint14/order-service.git
#       context: order-service
#       dockerfile: ./order-service/Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
      - zuul-gateway-server
      - postgres
