version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    container_name: eureka-server
    image: eureka-server
    build:
      context: eureka-server
      dockerfile: ./eureka-server/Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - postgres

  zuul-gateway-server:
    container_name: zuul-gateway-server
    image: zuul-gateway-server
    build:
      context: zuul-gateway-server
      dockerfile: ./zuul-gateway-server/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - eureka-server

  auth-service:
    container_name: auth-service
    image: auth-service
    build:
      context: auth-service
      dockerfile: ./auth-service/Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - postgres
      - eureka-server
      - zuul-gateway-server

  order-service:
    container_name: order-service
    image: order-service
    build:
      context: order-service
      dockerfile: ./order-service/Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - postgres
      - eureka-server
      - zuul-gateway-server
      - auth-service
